### ISSUE TITLE
libgs.9.21.dylib twice in folder structure

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-gs#1]
Hi Miyako,

thanks for the new update.

The libgs.9.21.dylib is 2x available inside the plugin folder structure. Is the frameworks folder needed ?
My currently in use plugin version 1.3 does not have the frameworks folder.
I also notoced, that the libgs.9.21.dylib reduced the file size from 45.4 MB to 23.2MB

![gs_screen](https://user-images.githubusercontent.com/6436037/82043383-c8c2b900-96ab-11ea-9b50-3a5bd7e65e6b.png)

Armin

**Comment by miyako** [comment]
Good catch! No it is not necessary to have the library in both locations, The ``Frameworks`` folder was probably created by Xcode automatically. 

As for the file size, it is approximately half because we no longer need i386 (32-bit) support.

**Comment by miyako** [comment]
https://github.com/miyako/4d-plugin-gs/releases/tag/2.0.1
