### ISSUE TITLE
GS not working on Windows

### ISSUE THREAD

**Issue by DenisJager** [miyako/4d-plugin-gs#3]
Hi Miyako,

I developed a little tool to spilt PDF in many parts. It perfectly works on Mac but doesn't work on windows 10. The command to extract a page doesn't create the file 1.txt that it should.

I updated the plugin from 1.3 to 2.3 but the issue is still the same...

Here is the code :

ARRAY TEXT($args;0)
APPEND TO ARRAY($args;"-dNOPAUSE")  //important, we can't interact with the cli
APPEND TO ARRAY($args;"-dBATCH")
APPEND TO ARRAY($args;"-dQUIET")
APPEND TO ARRAY($args;"-sDEVICE=pdfwrite")
//APPEND TO ARRAY($args; "-dCompatibilityLevel=1.7")
APPEND TO ARRAY($args;"-dFirstPage="+"1")
APPEND TO ARRAY($args;"-dLastPage="+"1")
APPEND TO ARRAY($args;"-sOutputFile="+PosixOutPath)  //output => 1.txt, 2.txt, etc.
  //command
APPEND TO ARRAY($args;"-c")
APPEND TO ARRAY($args;".setpdfwrite")
  //input
APPEND TO ARRAY($args;"-f")
APPEND TO ARRAY($args; PosixInPath)  //Input
GS ($args)

Do you have any idea of what goes wrong?
Best.
Denis

**Comment by DenisJager** [comment]
Hi Miyako,
Some extra information :

- It used to work on windows 10 then a change has been made (maybe a system update on my customer's computer ??) and then doesn't work anymore.

- Error code on Windows 10 is -100 when I try to extract one page from a PDF document

**Comment by miyako** [comment]
to rule out the possibility that some DLL has been removed, could you please download the plugin again?

**Comment by DenisJager** [comment]
I already tried and tried again yesterday and this morning to replace the gs.bundle with the last version available 2.3.0 but no change...

**Comment by DenisJager** [comment]
Hi Miyako,
There were in fact 2 problems. The main was the use of ".setpdfwrite" in the parameters which is deprecated.
https://github.com/GravityMedia/Ghostscript/issues/6
It generated an error. Without this parameters everything works fine.
The second one is in relation with my customer network and the RW access limited on certain disks.
Thank you for your replies.
